#ifndef _HAL_INSTANCES_H_
#define _HAL_INSTANCES_H_

#include <hal_common.h>

#define HAL_RCC_BUS_BITPOS  28

#define HAL_RCC_PERIPH_BITPOS_MSK 0x0000001F

#if defined(STM32F030x6)

#define HAL_RCC_BUS_AHB   0
#define HAL_RCC_BUS_APB2  1
#define HAL_RCC_BUS_APB1  2

typedef enum
{
    HAL_RCC_DMA          = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_DMAEN_Pos,
    HAL_RCC_SRAM         = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_SRAMEN_Pos,
    HAL_RCC_FLITF        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_FLITFEN_Pos,
    HAL_RCC_CRC          = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_CRCEN_Pos,
    HAL_RCC_GPIOA        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOAEN_Pos,
    HAL_RCC_GPIOB        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOBEN_Pos,
    HAL_RCC_GPIOC        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOCEN_Pos,
    HAL_RCC_GPIOD        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIODEN_Pos,
    HAL_RCC_GPIOF        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOFEN_Pos,
    HAL_RCC_SYSCFGCOMP   = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SYSCFGCOMPEN_Pos,
    HAL_RCC_ADC          = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_ADCEN_Pos,
    HAL_RCC_TIM1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM1EN_Pos,
    HAL_RCC_SPI1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SPI1EN_Pos,
    HAL_RCC_USART1       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_USART1EN_Pos,
    HAL_RCC_TIM16        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM16EN_Pos,
    HAL_RCC_TIM17        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM17EN_Pos,
    HAL_RCC_DBGMCU       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_DBGMCUEN_Pos,
    HAL_RCC_TIM3         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM3EN_Pos,
    HAL_RCC_TIM14        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM14EN_Pos,
    HAL_RCC_WWDG         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_WWDGEN_Pos,
    HAL_RCC_I2C1         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_I2C1EN_Pos,
    HAL_RCC_PWR          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_PWREN_Pos,
} hal_rcc_periph_t;

#elif defined(STM32F042x6)

#define HAL_RCC_BUS_AHB   0
#define HAL_RCC_BUS_APB2  1
#define HAL_RCC_BUS_APB1  2

typedef enum
{
    HAL_RCC_DMA          = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_DMAEN_Pos,
    HAL_RCC_SRAM         = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_SRAMEN_Pos,
    HAL_RCC_FLITF        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_FLITFEN_Pos,
    HAL_RCC_CRC          = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_CRCEN_Pos,
    HAL_RCC_GPIOA        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOAEN_Pos,
    HAL_RCC_GPIOB        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOBEN_Pos,
    HAL_RCC_GPIOC        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOCEN_Pos,
    HAL_RCC_GPIOF        = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_GPIOFEN_Pos,
    HAL_RCC_TSC          = (HAL_RCC_BUS_AHB << HAL_RCC_BUS_BITPOS) | RCC_AHBENR_TSCEN_Pos,
    HAL_RCC_SYSCFGCOMP   = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SYSCFGCOMPEN_Pos,
    HAL_RCC_ADC          = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_ADCEN_Pos,
    HAL_RCC_TIM1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM1EN_Pos,
    HAL_RCC_SPI1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SPI1EN_Pos,
    HAL_RCC_USART1       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_USART1EN_Pos,
    HAL_RCC_TIM16        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM16EN_Pos,
    HAL_RCC_TIM17        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM17EN_Pos,
    HAL_RCC_DBGMCU       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_DBGMCUEN_Pos,
    HAL_RCC_TIM2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM2EN_Pos,
    HAL_RCC_TIM3         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM3EN_Pos,
    HAL_RCC_TIM14        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM14EN_Pos,
    HAL_RCC_WWDG         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_WWDGEN_Pos,
    HAL_RCC_SPI2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_SPI2EN_Pos,
    HAL_RCC_USART2       = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_USART2EN_Pos,
    HAL_RCC_I2C1         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_I2C1EN_Pos,
    HAL_RCC_USB          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_USBEN_Pos,
    HAL_RCC_CA           = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_CANEN_Pos,
    HAL_RCC_CRS          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_CRSEN_Pos,
    HAL_RCC_PWR          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_PWREN_Pos,
    HAL_RCC_CEC          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_CECEN_Pos,
} hal_rcc_periph_t;

#elif defined(STM32F407xx)

#define HAL_RCC_BUS_AHB1  0
#define HAL_RCC_BUS_AHB2  1
#define HAL_RCC_BUS_AHB3  2
#define HAL_RCC_BUS_APB1  3
#define HAL_RCC_BUS_APB2  4

typedef enum
{
    HAL_RCC_GPIOA        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOAEN_Pos,
    HAL_RCC_GPIOB        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOBEN_Pos,
    HAL_RCC_GPIOC        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOCEN_Pos,
    HAL_RCC_GPIOD        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIODEN_Pos,
    HAL_RCC_GPIO         = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOEEN_Pos,
    HAL_RCC_GPIOF        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOFEN_Pos,
    HAL_RCC_GPIOG        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOGEN_Pos,
    HAL_RCC_GPIOH        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOHEN_Pos,
    HAL_RCC_GPIOI        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_GPIOIEN_Pos,
    HAL_RCC_CRC          = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_CRCEN_Pos,
    HAL_RCC_BKPSRAM      = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_BKPSRAMEN_Pos,
    HAL_RCC_CCMDATARAM   = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_CCMDATARAMEN_Pos,
    HAL_RCC_DMA1         = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_DMA1EN_Pos,
    HAL_RCC_DMA2         = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_DMA2EN_Pos,
    HAL_RCC_ETHMAC       = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_ETHMACEN_Pos,
    HAL_RCC_ETHMACTX     = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_ETHMACTXEN_Pos,
    HAL_RCC_ETHMACRX     = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_ETHMACRXEN_Pos,
    HAL_RCC_ETHMACPTP    = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_ETHMACPTPEN_Pos,
    HAL_RCC_OTGHS        = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_OTGHSEN_Pos,
    HAL_RCC_OTGHSULPI    = (HAL_RCC_BUS_AHB1 << HAL_RCC_BUS_BITPOS) | RCC_AHB1ENR_OTGHSULPIEN_Pos,
    HAL_RCC_DCMI         = (HAL_RCC_BUS_AHB2 << HAL_RCC_BUS_BITPOS) | RCC_AHB2ENR_DCMIEN_Pos,
    HAL_RCC_RNG          = (HAL_RCC_BUS_AHB2 << HAL_RCC_BUS_BITPOS) | RCC_AHB2ENR_RNGEN_Pos,
    HAL_RCC_OTGFS        = (HAL_RCC_BUS_AHB2 << HAL_RCC_BUS_BITPOS) | RCC_AHB2ENR_OTGFSEN_Pos,
    HAL_RCC_FSMC         = (HAL_RCC_BUS_AHB3 << HAL_RCC_BUS_BITPOS) | RCC_AHB3ENR_FSMCEN_Pos,
    HAL_RCC_TIM2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM2EN_Pos,
    HAL_RCC_TIM3         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM3EN_Pos,
    HAL_RCC_TIM4         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM4EN_Pos,
    HAL_RCC_TIM5         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM5EN_Pos,
    HAL_RCC_TIM6         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM6EN_Pos,
    HAL_RCC_TIM7         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM7EN_Pos,
    HAL_RCC_TIM12        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM12EN_Pos,
    HAL_RCC_TIM13        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM13EN_Pos,
    HAL_RCC_TIM14        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_TIM14EN_Pos,
    HAL_RCC_WWDG         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_WWDGEN_Pos,
    HAL_RCC_SPI2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_SPI2EN_Pos,
    HAL_RCC_SPI3         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_SPI3EN_Pos,
    HAL_RCC_USART2       = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_USART2EN_Pos,
    HAL_RCC_USART3       = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_USART3EN_Pos,
    HAL_RCC_UART4        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_UART4EN_Pos,
    HAL_RCC_UART5        = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_UART5EN_Pos,
    HAL_RCC_I2C1         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_I2C1EN_Pos,
    HAL_RCC_I2C2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_I2C2EN_Pos,
    HAL_RCC_I2C3         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_I2C3EN_Pos,
    HAL_RCC_CAN1         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_CAN1EN_Pos,
    HAL_RCC_CAN2         = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_CAN2EN_Pos,
    HAL_RCC_PWR          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_PWREN_Pos,
    HAL_RCC_DAC          = (HAL_RCC_BUS_APB1 << HAL_RCC_BUS_BITPOS) | RCC_APB1ENR_DACEN_Pos,
    HAL_RCC_TIM1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM1EN_Pos,
    HAL_RCC_TIM8         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM8EN_Pos,
    HAL_RCC_USART1       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_USART1EN_Pos,
    HAL_RCC_USART6       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_USART6EN_Pos,
    HAL_RCC_ADC1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_ADC1EN_Pos,
    HAL_RCC_ADC2         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_ADC2EN_Pos,
    HAL_RCC_ADC3         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_ADC3EN_Pos,
    HAL_RCC_SDIO         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SDIOEN_Pos,
    HAL_RCC_SPI1         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SPI1EN_Pos,
    HAL_RCC_SYSCFG       = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_SYSCFGEN_Pos,
    HAL_RCC_TIM9         = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM9EN_Pos,
    HAL_RCC_TIM10        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM10EN_Pos,
    HAL_RCC_TIM11        = (HAL_RCC_BUS_APB2 << HAL_RCC_BUS_BITPOS) | RCC_APB2ENR_TIM11EN_Pos,
} hal_rcc_periph_t;

#else
#error "No target MCU specified."
#endif

#endif // _HAL_INSTANCES_H_
