language: bash

install:
    - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch

script:
    - echo "Creating nightly branch"
    - ./nightly_create.sh
    - git checkout nightly
    - git push -f https://${USERNAME}:${GITHUB_API_KEY}@${GH_REF} HEAD:nightly
